# Generated by Django 4.2.21 on 2025-06-01 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_remove_reservation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='image',
        ),
        migrations.AddField(
            model_name='tool',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
