# Generated by Django 4.2.21 on 2025-06-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_tool_image_tool_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='user',
        ),
    ]
